site_name: Warp Hint
nav:
  - Home: index.md
  - Features:
      - Alias Resolve: features/alias_resolve.md
      - Kernel Call: features/kernel_call.md
      - Output Marker: features/output_marker.md
      - Real Generic: features/real_generic.md
theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true
  nav_style: dark
