site_name: Warp Hint
site_url: https://windwhiterain.github.io/warp_hint
nav:
  - Alias Resolve: features/alias_resolve.md
  - Kernel Call: features/kernel_call.md
  - Output Marker: features/output_marker.md
  - Real Generic: features/real_generic.md
  - Wrapper Type: features/wrapper_type.md
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: cyan
  icon:
    logo: material/home
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.footer
    - navigation.expand
repo_url: https://github.com/windwhiterain/warp_hint
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences